name: Enable Auto-Merge

on:
  repository_dispatch:
    types: [repository-created] # Trigger when a repository is created

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/permissions \
            -d '{"enabled": true}'

      - name: Enable Auto-Merge via GraphQL
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation { enablePullRequestAutoMerge(input: { pullRequestId: \"PULL_REQUEST_ID\", mergeMethod: MERGE }) { clientMutationId } }"}' \
            https://api.github.com/graphql