name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Sort Test
      id: sort-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Sort Test
        setup-command: ''
        command: make test
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SORT-TEST_RESULTS: "${{steps.sort-test.outputs.result}}"
      with:
        runners: sort-test